baseURL = 'https://algometix.com/'
languageCode = 'en-us'
title = 'Algometix'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

